name: CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Node.js dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Check Formatting
        run: forge fmt --check

      - name: Build Contracts
        run: forge build --sizes

      - name: Run Tests
        run: forge test -vvv

  deploy:
    name: Deploy and Start Services
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Smart Contracts
        run: |
          cd contract
          forge script scripts/Deploy.s.sol --rpc-url ${{ secrets.SEPOLIA_URL }} --private-key ${{ secrets.PRIVATE_KEY }}
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }}

      - name: Start Backend
        run: |
          cd backend
          npm install
          npm start &

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
